package com.sentinel.hse;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * HseReportEntity — persists an AI-generated HSE Incident & Sustainability Impact Report.
 *
 * Lifecycle:
 *   DRAFT       — AI-generated, not yet reviewed
 *   APPROVED    — reviewed and approved by an HSE professional; feeds the ESG layer
 *   REJECTED    — rejected with notes; requires re-generation or manual edit
 *
 * The full report content is stored as a JSON string in the `report_json` column
 * so the complete structured report is always recoverable without re-calling the LLM.
 *
 * ESG promotion happens only when status transitions to APPROVED.
 */
@Entity
@Table(name = "hse_report", indexes = {
    @Index(name = "idx_hse_report_event",  columnList = "source_event_id"),
    @Index(name = "idx_hse_report_status", columnList = "status, generated_at DESC"),
    @Index(name = "idx_hse_report_site",   columnList = "site_id, generated_at DESC")
})
@Getter
@Setter
@NoArgsConstructor
public class HseReportEntity {

    @Id
    @Column(name = "report_id", length = 50)
    private String reportId;

    /** The event that triggered this report. */
    @Column(name = "source_event_id", length = 50, nullable = false)
    private String sourceEventId;

    @Column(name = "site_id", length = 20)
    private String siteId;

    @Column(name = "severity", length = 20)
    private String severity;

    /** DRAFT | APPROVED | REJECTED */
    @Column(name = "status", length = 20, nullable = false)
    private String status = STATUS_DRAFT;

    /** One-line headline for list views — extracted from executiveSummary.headline */
    @Column(name = "headline", length = 500)
    private String headline;

    /** Full structured report as JSON string. */
    @Column(name = "report_json", columnDefinition = "TEXT", nullable = false)
    private String reportJson;

    /** Whether the report was generated by LLM (true) or from the template fallback (false). */
    @Column(name = "ai_generated", nullable = false)
    private boolean aiGenerated = false;

    @Column(name = "generated_at", nullable = false)
    private LocalDateTime generatedAt;

    /** Who approved/rejected — set by the approve/reject endpoints. */
    @Column(name = "reviewed_by", length = 100)
    private String reviewedBy;

    @Column(name = "reviewed_at")
    private LocalDateTime reviewedAt;

    /** Free-text notes from the HSE manager on approval or rejection. */
    @Column(name = "human_notes", columnDefinition = "TEXT")
    private String humanNotes;

    /** Set to true once approved metrics have been extracted to the ESG layer. */
    @Column(name = "esg_promoted", nullable = false)
    private boolean esgPromoted = false;

    // ── Status constants ──────────────────────────────────────────────────────

    public static final String STATUS_DRAFT    = "DRAFT";
    public static final String STATUS_APPROVED = "APPROVED";
    public static final String STATUS_REJECTED = "REJECTED";

    // ── Factory ───────────────────────────────────────────────────────────────

    public static HseReportEntity create(String sourceEventId, String siteId,
                                         String severity, String headline,
                                         String reportJson, boolean aiGenerated) {
        HseReportEntity report = new HseReportEntity();
        report.setReportId("HSE-" + UUID.randomUUID().toString().substring(0, 8).toUpperCase());
        report.setSourceEventId(sourceEventId);
        report.setSiteId(siteId);
        report.setSeverity(severity);
        report.setHeadline(headline);
        report.setReportJson(reportJson);
        report.setAiGenerated(aiGenerated);
        report.setStatus(STATUS_DRAFT);
        report.setGeneratedAt(LocalDateTime.now());
        return report;
    }
}
