import type { Alert, DataQualitySummary, IngestBatch, SiteDetail, SiteRiskSummary, TelemetrySummary } from "@/lib/sentinel/types";

// Mock sites — Kenya Pipeline Company

export const mockSites: SiteRiskSummary[] = [
  {
    siteId: "SITE-003",
    siteName: "Makueni Pump Station",
    latitude: -0.30,
    longitude: 36.07,
    riskScore: 82,
    severityBand: "Critical",
    incidentCount: 14,
    pressureSpikeCount: 5,
    lastAuditDate: "2026-07-01",
    daysSinceLastAudit: 21,
    correctedRate: 0.12,
    rejectedRate: 0.18,
  },
  {
    siteId: "SITE-006",
    siteName: "Sinendet Pump Station",
    latitude: 0.05,
    longitude: 35.45,
    riskScore: 76,
    severityBand: "Critical",
    incidentCount: 12,
    pressureSpikeCount: 4,
    lastAuditDate: "2026-07-03",
    daysSinceLastAudit: 19,
    correctedRate: 0.10,
    rejectedRate: 0.15,
  },
  {
    siteId: "SITE-001",
    siteName: "Nairobi Terminal",
    latitude: -1.30,
    longitude: 36.85,
    riskScore: 45,
    severityBand: "Medium",
    incidentCount: 5,
    pressureSpikeCount: 1,
    lastAuditDate: "2026-07-15",
    daysSinceLastAudit: 7,
    correctedRate: 0.05,
    rejectedRate: 0.03,
  },
  {
    siteId: "SITE-002",
    siteName: "Mombasa Terminal",
    latitude: -4.05,
    longitude: 39.65,
    riskScore: 38,
    severityBand: "Medium",
    incidentCount: 4,
    pressureSpikeCount: 0,
    lastAuditDate: "2026-07-18",
    daysSinceLastAudit: 4,
    correctedRate: 0.04,
    rejectedRate: 0.02,
  },
  {
    siteId: "SITE-004",
    siteName: "Nakuru Depot",
    latitude: -0.30,
    longitude: 36.07,
    riskScore: 29,
    severityBand: "Low",
    incidentCount: 3,
    pressureSpikeCount: 0,
    lastAuditDate: "2026-07-19",
    daysSinceLastAudit: 3,
    correctedRate: 0.02,
    rejectedRate: 0.01,
  },
  {
    siteId: "SITE-005",
    siteName: "Eldoret Depot",
    latitude: 0.52,
    longitude: 35.27,
    riskScore: 22,
    severityBand: "Low",
    incidentCount: 2,
    pressureSpikeCount: 0,
    lastAuditDate: "2026-07-20",
    daysSinceLastAudit: 2,
    correctedRate: 0.01,
    rejectedRate: 0.0,
  },
];

// Mock alerts

export const mockAlerts: Alert[] = [
  {
    id: "alert-001",
    siteId: "SITE-003",
    siteName: "Makueni Pump Station",
    severity: "Critical",
    status: "active",
    title: "Pressure spike cluster detected",
    description: "5 consecutive readings with pressure exceeding 1000 PSI on Section E — Makueni Branch. Potential leading indicator for pipeline failure.",
    rule: "Pressure spike cluster (≥3 consecutive readings > 1000 PSI)",
    recordIds: ["TEL-000321", "TEL-000322", "TEL-000323", "TEL-000324", "TEL-000325"],
    createdAt: "2026-07-22T08:15:00Z",
  },
  {
    id: "alert-002",
    siteId: "SITE-006",
    siteName: "Sinendet Pump Station",
    severity: "Critical",
    status: "active",
    title: "High rejection rate detected",
    description: "15% of records rejected in latest batch — exceeds 10% site threshold. Combined with 4 pressure spikes this week.",
    rule: "Site rejection rate > 10%",
    recordIds: ["INC-02398", "INC-02399"],
    createdAt: "2026-07-22T07:45:00Z",
  },
  {
    id: "alert-003",
    siteId: "SITE-003",
    siteName: "Makueni Pump Station",
    severity: "High",
    status: "active",
    title: "Audit overdue — high risk site",
    description: "Last audit was 21 days ago. Threshold is 14 days for Critical-risk sites.",
    rule: "Audit frequency threshold (14d for Critical-risk)",
    recordIds: [],
    createdAt: "2026-07-22T06:00:00Z",
  },
  {
    id: "alert-004",
    siteId: "SITE-006",
    siteName: "Sinendet Pump Station",
    severity: "High",
    status: "acknowledged",
    title: "Sensor dropout pattern",
    description: "12 sensor dropout events in the last 7 days at Sinendet — 3× normal rate. Possible sensor degradation.",
    rule: "Sensor dropout frequency > 3× 30-day rolling average",
    recordIds: ["TEL-003801", "TEL-003802", "TEL-003803"],
    createdAt: "2026-07-21T14:30:00Z",
    acknowledgedAt: "2026-07-21T15:00:00Z",
    acknowledgedBy: "analyst@sentinel.io",
  },
  {
    id: "alert-005",
    siteId: "SITE-001",
    siteName: "Nairobi Terminal",
    severity: "Medium",
    status: "active",
    title: "Invalid coordinates detected",
    description: "Record INC-00140 has coordinates (0,0) — likely data entry error. Record rejected.",
    rule: "Valid coordinates (lat/lon within Kenya bounds)",
    recordIds: ["INC-00140"],
    createdAt: "2026-07-21T10:00:00Z",
  },
  {
    id: "alert-006",
    siteId: "SITE-002",
    siteName: "Mombasa Terminal",
    severity: "Medium",
    status: "resolved",
    title: "Duplicate incident IDs in batch",
    description: "Batch b-0032 contained 3 duplicate incident_id values.",
    rule: "Uniqueness (incident_id unique within batch)",
    recordIds: ["INC-00350", "INC-00351"],
    createdAt: "2026-07-20T16:00:00Z",
    acknowledgedAt: "2026-07-20T17:00:00Z",
    acknowledgedBy: "admin@sentinel.io",
  },
  {
    id: "alert-007",
    siteId: "SITE-004",
    siteName: "Nakuru Depot",
    severity: "Low",
    status: "resolved",
    title: "Score bounds violation auto-corrected",
    description: "compliance_score of 105 clamped to 100 — logged as corrected.",
    rule: "Score bounds (0–100)",
    recordIds: ["AUD-02212"],
    createdAt: "2026-07-19T09:00:00Z",
    acknowledgedAt: "2026-07-19T09:15:00Z",
    acknowledgedBy: "analyst@sentinel.io",
  },
];

// Mock data quality summary

export const mockQualitySummary: DataQualitySummary = {
  trusted: 18974,
  corrected: 327,
  review: 205,
  rejected: 294,
  total: 19800,
  passRate: 0.9748,
  gateStatus: "passed",
  threshold: 0.9,
  lastBatchId: "b-0034",
  lastBatchDate: "2026-07-22T08:00:00Z",
};

// Mock telemetry summary

export const mockTelemetrySummary: TelemetrySummary = {
  totalReadings: 4288,
  pressureSpikeCount: 9,
  sensorDropoutCount: 42,
  avgPressure: 398.5,
  avgFlowRate: 2987.3,
  avgTemperature: 30.2,
};

// Mock ingest batches

export const mockBatches: IngestBatch[] = [
  {
    batchId: "b-0034",
    sourceFilename: "incidents_2026-07-22.csv",
    rowCount: 340,
    sha256Checksum: "a3f2c8e1d4b5a6f7e8d9c0b1a2f3e4d5c6b7a8f9e0d1c2b3a4f5e6d7c8b9a0f1",
    ingestedAt: "2026-07-22T08:00:00Z",
    trustedCount: 298,
    correctedCount: 22,
    reviewCount: 12,
    rejectedCount: 8,
  },
  {
    batchId: "b-0033",
    sourceFilename: "pipeline_telemetry_batch1.csv",
    rowCount: 4343,
    sha256Checksum: "b4e3d9f2a5c6b7a8e9d0c1b2a3f4e5d6c7b8a9f0e1d2c3b4a5f6e7d8c9b0a1f2",
    ingestedAt: "2026-07-21T08:00:00Z",
    trustedCount: 4200,
    correctedCount: 55,
    reviewCount: 45,
    rejectedCount: 43,
  },
  {
    batchId: "b-0032",
    sourceFilename: "incidents_2026-07-20.csv",
    rowCount: 312,
    sha256Checksum: "c5f4e0a3b6d7c8b9a0e1d2c3b4a5f6e7d8c9b0a1f2e3d4c5b6a7f8e9d0c1b2a3",
    ingestedAt: "2026-07-20T08:00:00Z",
    trustedCount: 270,
    correctedCount: 25,
    reviewCount: 11,
    rejectedCount: 6,
  },
  {
    batchId: "b-0031",
    sourceFilename: "audits_2026-07-19.csv",
    rowCount: 298,
    sha256Checksum: "d6a5f1b4c7e8d9c0b1a2f3e4d5c6b7a8f9e0d1c2b3a4f5e6d7c8b9a0f1e2d3c4",
    ingestedAt: "2026-07-19T08:00:00Z",
    trustedCount: 265,
    correctedCount: 19,
    reviewCount: 8,
    rejectedCount: 6,
  },
  {
    batchId: "b-0030",
    sourceFilename: "pipeline_telemetry_batch2.csv",
    rowCount: 707,
    sha256Checksum: "e7b6a2c5d8f9e0d1c2b3a4f5e6d7c8b9a0f1e2d3c4b5a6f7e8d9c0b1a2f3e4d5",
    ingestedAt: "2026-07-18T08:00:00Z",
    trustedCount: 680,
    correctedCount: 12,
    reviewCount: 10,
    rejectedCount: 5,
  },
];

// Mock site detail

const mockSiteDetails: Record<string, SiteDetail> = {
  "SITE-003": {
    siteId: "SITE-003",
    siteName: "Makueni Pump Station",
    location: "Makueni County, Kenya",
    latitude: -0.30,
    longitude: 36.07,
    riskScore: 82,
    severityBand: "Critical",
    pressureSpikeCount: 5,
    incidents: [
      {
        incidentId: "INC-00459",
        siteId: "SITE-003",
        latitude: -0.285,
        longitude: 36.091,
        incidentDate: "2026-07-20",
        severity: "Critical",
        description: "Pipeline leak detected near Thange River — containment activated.",
        complianceScore: 28,
        decision: "rejected",
        decisionReason: "compliance_score below hard threshold (30)",
      },
      {
        incidentId: "INC-00460",
        siteId: "SITE-003",
        latitude: -0.292,
        longitude: 36.085,
        incidentDate: "2026-07-19",
        severity: "High",
        description: "Valve failure on Section E causing pressure drop downstream.",
        complianceScore: 52,
        decision: "review",
        decisionReason: "Severity High + compliance_score in ambiguous range (40-60)",
      },
      {
        incidentId: "INC-00385",
        siteId: "SITE-003",
        latitude: -0.305,
        longitude: 36.072,
        incidentDate: "2026-07-15",
        severity: "Medium",
        description: "Equipment maintenance overdue — pump station B.",
        complianceScore: 75,
        decision: "trusted",
        decisionReason: "All validation rules pass",
      },
    ],
    audits: [
      {
        auditId: "AUD-00198",
        siteId: "SITE-003",
        inspectionDate: "2026-07-01",
        auditor: "J. Mwangi",
        findings: "3 non-conformances: emergency response plan outdated, containment bunds cracked, environmental monitoring gaps.",
        complianceScore: 48,
        followUpRequired: true,
      },
      {
        auditId: "AUD-00185",
        siteId: "SITE-003",
        inspectionDate: "2026-06-15",
        auditor: "M. Ochieng",
        findings: "Leak detection system offline for 72hrs. Maintenance records incomplete.",
        complianceScore: 55,
        followUpRequired: true,
      },
    ],
    telemetryReadings: [
      {
        readingId: "TEL-000321",
        timestamp: "2026-07-22T07:45:00Z",
        site: "SITE-003",
        pipelineSection: "Section E — Makueni Branch",
        pressurePsi: 1150.0,
        flowRateBph: 2800.0,
        temperatureCelsius: 38.5,
        valveStatus: "Open",
        sensorId: "SNS-007",
      },
      {
        readingId: "TEL-000320",
        timestamp: "2026-07-22T07:30:00Z",
        site: "SITE-003",
        pipelineSection: "Section E — Makueni Branch",
        pressurePsi: 980.0,
        flowRateBph: 2750.0,
        temperatureCelsius: 37.2,
        valveStatus: "Open",
        sensorId: "SNS-007",
      },
    ],
  },
  "SITE-006": {
    siteId: "SITE-006",
    siteName: "Sinendet Pump Station",
    location: "Bomet County, Kenya",
    latitude: 0.05,
    longitude: 35.45,
    riskScore: 76,
    severityBand: "Critical",
    pressureSpikeCount: 4,
    incidents: [
      {
        incidentId: "INC-04410",
        siteId: "SITE-006",
        latitude: 0.065,
        longitude: 35.427,
        incidentDate: "2026-07-21",
        severity: "High",
        description: "Oil spill detected near lateral branch — environmental response deployed.",
        complianceScore: 39,
        decision: "rejected",
        decisionReason: "compliance_score below hard threshold (30)",
      },
      {
        incidentId: "INC-04411",
        siteId: "SITE-006",
        latitude: 0.058,
        longitude: 35.442,
        incidentDate: "2026-07-20",
        severity: "High",
        description: "Sensor malfunction caused false readings for 6 hours.",
        complianceScore: 48,
        decision: "review",
        decisionReason: "Severity High + compliance_score in ambiguous range (40-60)",
      },
    ],
    audits: [
      {
        auditId: "AUD-00201",
        siteId: "SITE-006",
        inspectionDate: "2026-07-03",
        auditor: "R. Kipchoge",
        findings: "4 critical non-conformances: corrosion on pipe joints, safety equipment expired, access control gaps, no leak detection calibration.",
        complianceScore: 38,
        followUpRequired: true,
      },
    ],
    telemetryReadings: [
      {
        readingId: "TEL-003801",
        timestamp: "2026-07-21T16:00:00Z",
        site: "SITE-006",
        pipelineSection: "Section D — Sinendet Lateral",
        pressurePsi: null,
        flowRateBph: 3100.0,
        temperatureCelsius: 32.0,
        valveStatus: "Open",
        sensorId: "SNS-012",
      },
    ],
  },
};

export function getMockSiteDetail(siteId: string): SiteDetail {
  if (mockSiteDetails[siteId]) {
    return mockSiteDetails[siteId];
  }

  // Generate a generic detail for sites without explicit mock data
  const site = mockSites.find((s) => s.siteId === siteId);
  return {
    siteId,
    siteName: site?.siteName ?? `Site ${siteId}`,
    location: "Kenya",
    latitude: site?.latitude ?? 0,
    longitude: site?.longitude ?? 0,
    riskScore: site?.riskScore ?? 0,
    severityBand: site?.severityBand ?? "Low",
    pressureSpikeCount: site?.pressureSpikeCount ?? 0,
    incidents: [],
    audits: [],
    telemetryReadings: [],
  };
}
