import type {
  Alert,
  ComplianceNetworkSummary,
  ComplianceSummary,
  ComplianceTrendPoint,
  ComplianceViolation,
  DataQualitySummary,
  IngestBatch,
  SiteDetail,
  SiteRiskSummary,
} from "@/lib/sentinel/types";

// ─── Mock Sites (Risk Summary) ─────────────────────────────────────────────

export const mockSites: SiteRiskSummary[] = [
  {
    siteId: "site-001",
    siteName: "Nairobi Terminal",
    riskScore: 62,
    severityBand: "High",
    incidentCount: 8,
    lastAuditDate: "2026-07-15",
    daysSinceLastAudit: 7,
    correctedRate: 0.06,
    rejectedRate: 0.09,
    latitude: -1.292,
    longitude: 36.822,
    pressureSpikeCount: 1,
  },
  {
    siteId: "site-002",
    siteName: "Mombasa Terminal (Kipevu / PS14)",
    riskScore: 74,
    severityBand: "High",
    incidentCount: 12,
    lastAuditDate: "2026-07-01",
    daysSinceLastAudit: 21,
    correctedRate: 0.10,
    rejectedRate: 0.18,
    latitude: -4.049,
    longitude: 39.674,
    pressureSpikeCount: 2,
  },
  {
    siteId: "site-003",
    siteName: "Makueni Pipeline Section (Thange)",
    riskScore: 82,
    severityBand: "Critical",
    incidentCount: 16,
    lastAuditDate: "2026-07-01",
    daysSinceLastAudit: 21,
    correctedRate: 0.12,
    rejectedRate: 0.18,
    latitude: -2.283,
    longitude: 37.833,
    pressureSpikeCount: 3,
  },
  {
    siteId: "site-004",
    siteName: "Nakuru Depot",
    riskScore: 45,
    severityBand: "Medium",
    incidentCount: 5,
    lastAuditDate: "2026-07-18",
    daysSinceLastAudit: 4,
    correctedRate: 0.04,
    rejectedRate: 0.05,
    latitude: -0.303,
    longitude: 36.080,
    pressureSpikeCount: 1,
  },
  {
    siteId: "site-005",
    siteName: "Eldoret Terminal",
    riskScore: 68,
    severityBand: "High",
    incidentCount: 10,
    lastAuditDate: "2026-07-05",
    daysSinceLastAudit: 17,
    correctedRate: 0.08,
    rejectedRate: 0.12,
    latitude: 0.517,
    longitude: 35.268,
    pressureSpikeCount: 2,
  },
  {
    siteId: "site-006",
    siteName: "Sinendet Pump Station",
    riskScore: 79,
    severityBand: "High",
    incidentCount: 14,
    lastAuditDate: "2026-07-03",
    daysSinceLastAudit: 19,
    correctedRate: 0.11,
    rejectedRate: 0.20,
    latitude: 0.043,
    longitude: 35.451,
    pressureSpikeCount: 3,
  },
  {
    siteId: "site-007",
    siteName: "Kisumu Terminal (PS28)",
    riskScore: 28,
    severityBand: "Low",
    incidentCount: 2,
    lastAuditDate: "2026-07-20",
    daysSinceLastAudit: 2,
    correctedRate: 0.02,
    rejectedRate: 0.01,
    latitude: -0.102,
    longitude: 34.762,
    pressureSpikeCount: 0,
  },
];

// ─── Mock Alerts ────────────────────────────────────────────────────────────

export const mockAlerts: Alert[] = [
  {
    id: "alert-001",
    siteId: "site-006",
    siteName: "Sinendet Pump Station",
    severity: "Critical",
    status: "active",
    title: "Data quality gate failed — Sinendet",
    description: "Trusted+corrected rate at Sinendet Pump Station dropped below 90% threshold. Current rate: 63%.",
    rule: "DQ gate threshold (--fail-below 0.90)",
    recordIds: ["INC-2026-0441", "INC-2026-0442", "INC-2026-0443"],
    createdAt: "2026-07-22T08:15:00Z",
  },
  {
    id: "alert-002",
    siteId: "site-003",
    siteName: "Makueni Pipeline Section (Thange)",
    severity: "Critical",
    status: "active",
    title: "High rejection rate — Makueni",
    description: "18% of records rejected in latest batch at Makueni Pump Station — exceeds 10% site threshold.",
    rule: "Site rejection rate > 10%",
    recordIds: ["INC-2026-0459", "INC-2026-0460"],
    createdAt: "2026-07-22T07:45:00Z",
  },
  {
    id: "alert-003",
    siteId: "site-003",
    siteName: "Makueni Pipeline Section (Thange)",
    severity: "High",
    status: "active",
    title: "Audit overdue — Makueni Pump Station",
    description: "Last audit was 21 days ago. Threshold is 14 days for Critical-risk sites.",
    rule: "Audit frequency threshold (14d for Critical-risk)",
    recordIds: [],
    createdAt: "2026-07-22T06:00:00Z",
  },
  {
    id: "alert-004",
    siteId: "site-006",
    siteName: "Sinendet Pump Station",
    severity: "High",
    status: "acknowledged",
    title: "Containment integrity gap preceded spill incident",
    description: "Audit AUD-2026-0201 found containment non-conformances with no corrective action. Oil spill followed 18 days later.",
    rule: "Unresolved audit finding preceding incident of same type",
    recordIds: ["AUD-2026-0201", "INC-2026-0441"],
    createdAt: "2026-07-21T14:30:00Z",
    acknowledgedAt: "2026-07-21T15:00:00Z",
    acknowledgedBy: "analyst@sentinel.kpc",
  },
  {
    id: "alert-005",
    siteId: "site-004",
    siteName: "Nakuru Depot",
    severity: "Medium",
    status: "active",
    title: "Future incident date detected",
    description: "Record INC-2026-0388 has incident_date (2026-07-25) after ingestion date (2026-07-22).",
    rule: "No future incidents (validate.py rule)",
    recordIds: ["INC-2026-0388"],
    createdAt: "2026-07-21T10:00:00Z",
  },
  {
    id: "alert-006",
    siteId: "site-002",
    siteName: "Mombasa Terminal (Kipevu / PS14)",
    severity: "High",
    status: "resolved",
    title: "Incident frequency spike — Mombasa Terminal",
    description: "9 incidents in the last 30 days at Mombasa Terminal — 3× rolling 90-day average.",
    rule: "Incident frequency > 3× 90-day rolling average",
    recordIds: ["INC-2026-0370", "INC-2026-0371"],
    createdAt: "2026-07-20T16:00:00Z",
    acknowledgedAt: "2026-07-20T17:00:00Z",
    acknowledgedBy: "admin@sentinel.kpc",
  },
  {
    id: "alert-007",
    siteId: "site-001",
    siteName: "Nairobi Terminal",
    severity: "Low",
    status: "resolved",
    title: "Score bounds violation auto-corrected",
    description: "compliance_score of 105 clamped to 100 — logged as corrected in batch b-0033.",
    rule: "Score bounds (0–100)",
    recordIds: ["AUD-2026-0212"],
    createdAt: "2026-07-19T09:00:00Z",
    acknowledgedAt: "2026-07-19T09:15:00Z",
    acknowledgedBy: "analyst@sentinel.kpc",
  },
];

// ─── Mock Data Quality Summary ──────────────────────────────────────────────

export const mockQualitySummary: DataQualitySummary = {
  trusted: 1847,
  corrected: 203,
  review: 89,
  rejected: 61,
  total: 2200,
  passRate: 0.9318,
  gateStatus: "passed",
  threshold: 0.9,
  lastBatchId: "b-0034",
  lastBatchDate: "2026-07-22T08:00:00Z",
};

// ─── Mock Ingest Batches ────────────────────────────────────────────────────

export const mockBatches: IngestBatch[] = [
  {
    batchId: "b-0034",
    sourceFilename: "incidents_2026-07-22.csv",
    rowCount: 340,
    sha256Checksum: "a3f2c8e1d4b5a6f7e8d9c0b1a2f3e4d5c6b7a8f9e0d1c2b3a4f5e6d7c8b9a0f1",
    ingestedAt: "2026-07-22T08:00:00Z",
    trustedCount: 298,
    correctedCount: 22,
    reviewCount: 12,
    rejectedCount: 8,
  },
  {
    batchId: "b-0033",
    sourceFilename: "incidents_2026-07-21.csv",
    rowCount: 285,
    sha256Checksum: "b4e3d9f2a5c6b7a8e9d0c1b2a3f4e5d6c7b8a9f0e1d2c3b4a5f6e7d8c9b0a1f2",
    ingestedAt: "2026-07-21T08:00:00Z",
    trustedCount: 252,
    correctedCount: 18,
    reviewCount: 9,
    rejectedCount: 6,
  },
  {
    batchId: "b-0032",
    sourceFilename: "incidents_2026-07-20.csv",
    rowCount: 312,
    sha256Checksum: "c5f4e0a3b6d7c8b9a0e1d2c3b4a5f6e7d8c9b0a1f2e3d4c5b6a7f8e9d0c1b2a3",
    ingestedAt: "2026-07-20T08:00:00Z",
    trustedCount: 270,
    correctedCount: 25,
    reviewCount: 11,
    rejectedCount: 6,
  },
  {
    batchId: "b-0031",
    sourceFilename: "incidents_2026-07-19.csv",
    rowCount: 298,
    sha256Checksum: "d6a5f1b4c7e8d9c0b1a2f3e4d5c6b7a8f9e0d1c2b3a4f5e6d7c8b9a0f1e2d3c4",
    ingestedAt: "2026-07-19T08:00:00Z",
    trustedCount: 265,
    correctedCount: 19,
    reviewCount: 8,
    rejectedCount: 6,
  },
  {
    batchId: "b-0030",
    sourceFilename: "incidents_2026-07-18.csv",
    rowCount: 275,
    sha256Checksum: "e7b6a2c5d8f9e0d1c2b3a4f5e6d7c8b9a0f1e2d3c4b5a6f7e8d9c0b1a2f3e4d5",
    ingestedAt: "2026-07-18T08:00:00Z",
    trustedCount: 240,
    correctedCount: 20,
    reviewCount: 10,
    rejectedCount: 5,
  },
];

// ─── Mock Site Detail ───────────────────────────────────────────────────────

const mockSiteDetails: Record<string, SiteDetail> = {
  "site-001": {
    siteId: "site-001",
    siteName: "Nairobi Terminal",
    location: "Nairobi, Kenya",
    riskScore: 62,
    severityBand: "High",
    latitude: -1.292,
    longitude: 36.822,
    pressureSpikeCount: 1,
    incidentCount: 4,
    critHighCount: 2,
    daysSinceAudit: 7,
    rejectedRate: 0.25,
    telemetryReadings: [],
    incidents: [
      {
        incidentId: "INC-2026-0398",
        siteId: "site-001",
        incidentDate: "2026-07-20",
        severity: "Critical",
        description: "Unauthorized access to restricted zone — perimeter breach detected by sensor grid.",
        complianceScore: 28,
        decision: "rejected",
        decisionReason: "compliance_score below hard threshold (30)",
      },
      {
        incidentId: "INC-2026-0399",
        siteId: "site-001",
        incidentDate: "2026-07-19",
        severity: "High",
        description: "Fuel storage temperature exceeded safe range for 4+ hours.",
        complianceScore: 52,
        decision: "review",
        decisionReason: "Severity High + compliance_score in ambiguous range (40-60)",
      },
      {
        incidentId: "INC-2026-0385",
        siteId: "site-001",
        incidentDate: "2026-07-15",
        severity: "Medium",
        description: "PPE non-compliance observed during routine check.",
        complianceScore: 75,
        decision: "trusted",
        decisionReason: "All validation rules pass",
      },
      {
        incidentId: "INC-2026-0372",
        siteId: "site-001",
        incidentDate: "2026-07-10",
        severity: "High",
        description: "Fire suppression system offline for scheduled maintenance — extended beyond window.",
        complianceScore: 60,
        decision: "corrected",
        decisionReason: "severity normalized from 'high' to 'High' (case correction)",
        closedDate: "2026-07-12",
      },
    ],
    audits: [
      {
        auditId: "AUD-2026-0212",
        siteId: "site-001",
        inspectionDate: "2026-07-15",
        auditor: "M. Ochieng",
        findings: "Satisfactory compliance. Score bounds violation auto-corrected (105 → 100).",
        complianceScore: 88,
        followUpRequired: false,
      },
      {
        auditId: "AUD-2026-0185",
        siteId: "site-001",
        inspectionDate: "2026-06-15",
        auditor: "M. Ochieng",
        findings: "Minor equipment calibration records gap. All safety certifications current.",
        complianceScore: 78,
        followUpRequired: false,
      },
    ],
  },
  "site-003": {
    siteId: "site-003",
    siteName: "Makueni Pipeline Section (Thange)",
    location: "Makueni County, Kenya",
    riskScore: 82,
    severityBand: "Critical",
    latitude: -2.283,
    longitude: 37.833,
    pressureSpikeCount: 3,
    incidentCount: 4,
    critHighCount: 3,
    daysSinceAudit: 21,
    rejectedRate: 0.50,
    telemetryReadings: [],
    incidents: [
      {
        incidentId: "INC-2026-0459",
        siteId: "site-003",
        incidentDate: "2026-07-20",
        severity: "Critical",
        description: "Pipeline leak detected near Thange River crossing — containment bunds activated.",
        complianceScore: 28,
        decision: "rejected",
        decisionReason: "compliance_score below hard threshold (30)",
      },
      {
        incidentId: "INC-2026-0460",
        siteId: "site-003",
        incidentDate: "2026-07-19",
        severity: "High",
        description: "Valve failure on Section E causing pressure drop downstream — pump isolated.",
        complianceScore: 52,
        decision: "review",
        decisionReason: "Severity High + compliance_score in ambiguous range (40-60)",
      },
      {
        incidentId: "INC-2026-0385",
        siteId: "site-003",
        incidentDate: "2026-07-15",
        severity: "Medium",
        description: "Leak detection sensor offline for 6 hours — maintenance window overrun.",
        complianceScore: 75,
        decision: "trusted",
        decisionReason: "All validation rules pass",
      },
      {
        incidentId: "INC-2026-0372",
        siteId: "site-003",
        incidentDate: "2026-07-10",
        severity: "High",
        description: "Containment bund integrity failure observed during routine inspection.",
        complianceScore: 60,
        decision: "corrected",
        decisionReason: "severity normalized from 'high' to 'High' (case correction)",
        closedDate: "2026-07-12",
      },
    ],
    audits: [
      {
        auditId: "AUD-2026-0198",
        siteId: "site-003",
        inspectionDate: "2026-07-01",
        auditor: "J. Mwangi",
        findings: "Three non-conformances: emergency response plan outdated, containment bunds cracked, environmental monitoring gaps.",
        complianceScore: 48,
        followUpRequired: true,
      },
      {
        auditId: "AUD-2026-0185",
        siteId: "site-003",
        inspectionDate: "2026-06-15",
        auditor: "M. Ochieng",
        findings: "Leak detection system offline for 72hrs. Maintenance records incomplete for Section E.",
        complianceScore: 55,
        followUpRequired: true,
      },
    ],
  },
};

export function getMockSiteDetail(siteId: string): SiteDetail {
  if (mockSiteDetails[siteId]) {
    return mockSiteDetails[siteId];
  }

  // Generate a generic detail for sites without explicit mock data
  const site = mockSites.find((s) => s.siteId === siteId);
  return {
    siteId,
    siteName: site?.siteName ?? `Site ${siteId}`,
    location: "Unknown",
    riskScore: site?.riskScore ?? 0,
    severityBand: site?.severityBand ?? "Low",
    latitude: 0,
    longitude: 0,
    pressureSpikeCount: 0,
    incidentCount: 0,
    critHighCount: 0,
    daysSinceAudit: 365,
    rejectedRate: 0,
    telemetryReadings: [],
    incidents: [],
    audits: [],
  };
}

// ─── Mock Compliance Data ───────────────────────────────────────────────────

export const mockComplianceNetwork: ComplianceNetworkSummary = {
  networkOcs: 82.4,
  networkSafetyScore: 79.8,
  networkEnvironmentalScore: 85.2,
  networkAssetIntegrityScore: 81.6,
  networkRegulatoryScore: 83.9,
  networkRag: "AMBER",
  totalOpenViolations: 14,
  totalCriticalViolations: 3,
  calculatedAt: "2026-07-24T06:00:00Z",
  sites: [
    { siteId: "site-001", siteName: "Nairobi Terminal",                  region: "Nairobi",     criticality: "Critical", overallScore: 80.1, overallRag: "AMBER", safetyScore: 79.5, safetyRag: "AMBER", environmentalScore: 82.0, environmentalRag: "AMBER", assetIntegrityScore: 79.0, assetIntegrityRag: "AMBER", regulatoryScore: 80.0, regulatoryRag: "AMBER", openViolations: 3 },
    { siteId: "site-002", siteName: "Mombasa Terminal (Kipevu / PS14)",  region: "Coast",       criticality: "Critical", overallScore: 74.1, overallRag: "RED",   safetyScore: 68.0, safetyRag: "RED",   environmentalScore: 80.0, environmentalRag: "AMBER", assetIntegrityScore: 76.0, assetIntegrityRag: "AMBER", regulatoryScore: 75.0, regulatoryRag: "AMBER", openViolations: 3 },
    { siteId: "site-003", siteName: "Makueni Pipeline Section (Thange)", region: "Makueni",     criticality: "Critical", overallScore: 69.4, overallRag: "RED",   safetyScore: 64.0, safetyRag: "RED",   environmentalScore: 76.0, environmentalRag: "AMBER", assetIntegrityScore: 68.0, assetIntegrityRag: "RED",   regulatoryScore: 72.0, regulatoryRag: "RED",   openViolations: 4 },
    { siteId: "site-004", siteName: "Nakuru Depot",                      region: "Rift Valley", criticality: "High",     overallScore: 78.3, overallRag: "AMBER", safetyScore: 80.0, safetyRag: "AMBER", environmentalScore: 84.0, environmentalRag: "AMBER", assetIntegrityScore: 71.0, assetIntegrityRag: "RED",   regulatoryScore: 80.0, regulatoryRag: "AMBER", openViolations: 2 },
    { siteId: "site-005", siteName: "Eldoret Terminal",                  region: "Rift Valley", criticality: "High",     overallScore: 71.2, overallRag: "RED",   safetyScore: 75.0, safetyRag: "AMBER", environmentalScore: 82.0, environmentalRag: "AMBER", assetIntegrityScore: 62.0, assetIntegrityRag: "RED",   regulatoryScore: 78.0, regulatoryRag: "AMBER", openViolations: 3 },
    { siteId: "site-006", siteName: "Sinendet Pump Station",             region: "Bomet",       criticality: "Critical", overallScore: 68.0, overallRag: "RED",   safetyScore: 70.0, safetyRag: "RED",   environmentalScore: 64.0, environmentalRag: "RED",   assetIntegrityScore: 70.0, assetIntegrityRag: "RED",   regulatoryScore: 70.0, regulatoryRag: "RED",   openViolations: 4 },
    { siteId: "site-007", siteName: "Kisumu Terminal (PS28)",            region: "Nyanza",      criticality: "High",     overallScore: 88.0, overallRag: "GREEN", safetyScore: 90.0, safetyRag: "GREEN", environmentalScore: 91.0, environmentalRag: "GREEN", assetIntegrityScore: 85.0, assetIntegrityRag: "AMBER", regulatoryScore: 87.0, regulatoryRag: "GREEN", openViolations: 1 },
  ],
};

export const mockViolations: ComplianceViolation[] = [
  { id: 1, ruleId: "BR-S03", ruleName: "PTW Authorisation Before High-Risk Work",     indicatorId: "PTWCI", domainId: "SCD",  siteId: "site-002", siteName: "Mombasa Terminal (Kipevu / PS14)",  assetReference: "CMP-INC-0002", severity: "Critical", violationDate: "2026-07-03", description: "Hot work commenced on Mombasa manifold without valid PTW.",                                      recommendedAction: "Immediate stop-work; mandatory PTW refresher for all supervisors.",                        status: "OPEN",  closedDate: null, createdAt: "2026-07-22T08:00:00Z" },
  { id: 2, ruleId: "BR-A04", ruleName: "Leak Detection System Availability",           indicatorId: "LDCI",  domainId: "AICD", siteId: "site-005", siteName: "Eldoret Terminal",                  assetReference: "CMP-INC-0005", severity: "Critical", violationDate: "2026-07-08", description: "SCADA CPM unavailable for 2.5 hours on Eldoret segment.",                                         recommendedAction: "Immediate SCADA team alert; manual patrol during downtime; investigate root cause.",        status: "OPEN",  closedDate: null, createdAt: "2026-07-22T08:00:00Z" },
  { id: 3, ruleId: "BR-S03", ruleName: "PTW Authorisation Before High-Risk Work",     indicatorId: "PTWCI", domainId: "SCD",  siteId: "site-003", siteName: "Makueni Pipeline Section (Thange)",  assetReference: "CMP-INC-0017", severity: "Critical", violationDate: "2026-07-07", description: "Confined space entry without completed gas test at Makueni section.",                              recommendedAction: "Stop-work; disciplinary review; mandatory confined space PTW re-briefing.",                status: "OPEN",  closedDate: null, createdAt: "2026-07-22T08:00:00Z" },
  { id: 4, ruleId: "BR-A01", ruleName: "Asset Inspection Not Overdue",                 indicatorId: "ICI",   domainId: "AICD", siteId: "site-001", siteName: "Nairobi Terminal",                  assetReference: "NBW-PV-003",   severity: "High",     violationDate: "2026-07-20", description: "Pressure vessel NBW-PV-003 inspection 38 days overdue.",                                          recommendedAction: "Schedule inspection immediately; conduct risk assessment pending inspection.",               status: "OPEN",  closedDate: null, createdAt: "2026-07-22T08:00:00Z" },
  { id: 5, ruleId: "BR-E01", ruleName: "Water Discharge Parameter Within NEMA Limits", indicatorId: "WQCI",  domainId: "ECD",  siteId: "site-006", siteName: "Sinendet Pump Station",             assetReference: "CMP-INC-0019", severity: "High",     violationDate: "2026-07-09", description: "TPH level 1.4x NEMA permitted limit at Sinendet Station.",                                       recommendedAction: "Identify source; isolate discharge; notify NEMA within 24h; inspect oil/water separator.", status: "OPEN",  closedDate: null, createdAt: "2026-07-22T08:00:00Z" },
  { id: 6, ruleId: "BR-A03", ruleName: "Corrosion Monitoring Point Coverage",          indicatorId: "CMCI",  domainId: "AICD", siteId: "site-004", siteName: "Nakuru Depot",                      assetReference: "NKR-012",       severity: "High",     violationDate: "2026-07-14", description: "Segment NKR-012 corrosion monitoring point 18 days past required interval.",                   recommendedAction: "Dispatch corrosion technician; verify CP system; schedule immediate reading.",              status: "OPEN",  closedDate: null, createdAt: "2026-07-22T08:00:00Z" },
  { id: 7, ruleId: "BR-R02", ruleName: "Corrective Action Closed By Target Date",     indicatorId: "CACI",  domainId: "RCD",  siteId: "site-001", siteName: "Nairobi Terminal",                  assetReference: "CAR-2026-0047", severity: "High",     violationDate: "2026-06-13", description: "CAR-2026-0047 (leak detection calibration) is 41 days past target date.",                      recommendedAction: "Escalate to Maintenance Superintendent; resolve within 5 working days.",                   status: "OPEN",  closedDate: null, createdAt: "2026-07-22T08:00:00Z" },
  { id: 8, ruleId: "BR-S01", ruleName: "PPE Field Observation Compliance",            indicatorId: "PCI",   domainId: "SCD",  siteId: "site-002", siteName: "Mombasa Terminal (Kipevu / PS14)",  assetReference: "CMP-INC-0001", severity: "High",     violationDate: "2026-07-01", description: "3 workers observed without hard hats in pump hall.",                                              recommendedAction: "Issue verbal warning; toolbox talk within 24h; re-inspect within 48h.",                    status: "OPEN",  closedDate: null, createdAt: "2026-07-22T08:00:00Z" },
];

export const mockComplianceTrend: ComplianceTrendPoint[] = [
  { weekStart: "2026-05-19", ocsScore: 88.2, safetyScore: 86.0, environmentalScore: 90.1, assetIntegrityScore: 87.5, regulatoryScore: 89.2 },
  { weekStart: "2026-05-26", ocsScore: 87.6, safetyScore: 85.4, environmentalScore: 89.8, assetIntegrityScore: 86.8, regulatoryScore: 88.7 },
  { weekStart: "2026-06-02", ocsScore: 86.9, safetyScore: 84.9, environmentalScore: 89.2, assetIntegrityScore: 85.9, regulatoryScore: 88.0 },
  { weekStart: "2026-06-09", ocsScore: 86.1, safetyScore: 84.1, environmentalScore: 88.6, assetIntegrityScore: 85.0, regulatoryScore: 87.2 },
  { weekStart: "2026-06-16", ocsScore: 85.4, safetyScore: 83.4, environmentalScore: 87.9, assetIntegrityScore: 84.2, regulatoryScore: 86.5 },
  { weekStart: "2026-06-23", ocsScore: 84.8, safetyScore: 82.8, environmentalScore: 87.3, assetIntegrityScore: 83.4, regulatoryScore: 85.8 },
  { weekStart: "2026-06-30", ocsScore: 84.0, safetyScore: 82.1, environmentalScore: 86.6, assetIntegrityScore: 82.5, regulatoryScore: 85.0 },
  { weekStart: "2026-07-07", ocsScore: 83.3, safetyScore: 81.4, environmentalScore: 86.0, assetIntegrityScore: 81.7, regulatoryScore: 84.3 },
  { weekStart: "2026-07-14", ocsScore: 83.5, safetyScore: 80.8, environmentalScore: 86.4, assetIntegrityScore: 82.8, regulatoryScore: 84.8 },
  { weekStart: "2026-07-21", ocsScore: 82.4, safetyScore: 79.8, environmentalScore: 85.2, assetIntegrityScore: 81.6, regulatoryScore: 83.9 },
];

export function getMockComplianceSite(siteId: string): ComplianceSummary {
  const card = mockComplianceNetwork.sites.find((s) => s.siteId === siteId);
  const name = card?.siteName ?? siteId;
  return {
    siteId,
    siteName: name,
    overallScore: card?.overallScore ?? 82.4,
    overallRag: card?.overallRag ?? "AMBER",
    openViolationCount: card?.openViolations ?? 0,
    criticalViolationCount: 0,
    periodStart: "2026-06-24",
    periodEnd: "2026-07-24",
    calculatedAt: "2026-07-24T06:00:00Z",
    domains: [
      { domainId: "SCD",  domainName: "Safety Compliance",          domainWeight: 0.30, score: card?.safetyScore ?? 80,           ragStatus: card?.safetyRag ?? "AMBER",           displayOrder: 1, indicators: [] },
      { domainId: "ECD",  domainName: "Environmental Compliance",   domainWeight: 0.25, score: card?.environmentalScore ?? 85,    ragStatus: card?.environmentalRag ?? "AMBER",    displayOrder: 2, indicators: [] },
      { domainId: "AICD", domainName: "Asset Integrity Compliance", domainWeight: 0.25, score: card?.assetIntegrityScore ?? 82,   ragStatus: card?.assetIntegrityRag ?? "AMBER",   displayOrder: 3, indicators: [] },
      { domainId: "RCD",  domainName: "Regulatory Compliance",      domainWeight: 0.20, score: card?.regulatoryScore ?? 84,       ragStatus: card?.regulatoryRag ?? "GREEN",       displayOrder: 4, indicators: [] },
    ],
  };
}
