import type {
  Alert,
  ComplianceNetworkSummary,
  ComplianceSummary,
  ComplianceTrendPoint,
  ComplianceViolation,
  DataQualitySummary,
  IngestBatch,
  SiteDetail,
  SiteRiskSummary,
} from "@/lib/sentinel/types";

// ─── Mock Sites (Risk Summary) ─────────────────────────────────────────────

export const mockSites: SiteRiskSummary[] = [
  {
    siteId: "site-001",
    siteName: "Melbourne Central",
    riskScore: 82,
    severityBand: "Critical",
    incidentCount: 14,
    lastAuditDate: "2026-07-01",
    daysSinceLastAudit: 21,
    correctedRate: 0.12,
    rejectedRate: 0.18,
  },
  {
    siteId: "site-002",
    siteName: "Brisbane North",
    riskScore: 67,
    severityBand: "High",
    incidentCount: 9,
    lastAuditDate: "2026-07-10",
    daysSinceLastAudit: 12,
    correctedRate: 0.08,
    rejectedRate: 0.1,
  },
  {
    siteId: "site-003",
    siteName: "Sydney Harbour",
    riskScore: 45,
    severityBand: "Medium",
    incidentCount: 5,
    lastAuditDate: "2026-07-15",
    daysSinceLastAudit: 7,
    correctedRate: 0.05,
    rejectedRate: 0.03,
  },
  {
    siteId: "site-004",
    siteName: "Perth West",
    riskScore: 23,
    severityBand: "Low",
    incidentCount: 2,
    lastAuditDate: "2026-07-18",
    daysSinceLastAudit: 4,
    correctedRate: 0.02,
    rejectedRate: 0.01,
  },
  {
    siteId: "site-005",
    siteName: "Adelaide South",
    riskScore: 71,
    severityBand: "High",
    incidentCount: 11,
    lastAuditDate: "2026-07-05",
    daysSinceLastAudit: 17,
    correctedRate: 0.09,
    rejectedRate: 0.14,
  },
  {
    siteId: "site-006",
    siteName: "Hobart Docks",
    riskScore: 38,
    severityBand: "Medium",
    incidentCount: 4,
    lastAuditDate: "2026-07-19",
    daysSinceLastAudit: 3,
    correctedRate: 0.04,
    rejectedRate: 0.02,
  },
  {
    siteId: "site-007",
    siteName: "Darwin Port",
    riskScore: 56,
    severityBand: "Medium",
    incidentCount: 7,
    lastAuditDate: "2026-07-12",
    daysSinceLastAudit: 10,
    correctedRate: 0.06,
    rejectedRate: 0.07,
  },
  {
    siteId: "site-008",
    siteName: "Canberra HQ",
    riskScore: 15,
    severityBand: "Low",
    incidentCount: 1,
    lastAuditDate: "2026-07-20",
    daysSinceLastAudit: 2,
    correctedRate: 0.01,
    rejectedRate: 0.0,
  },
  {
    siteId: "site-009",
    siteName: "Gold Coast Marina",
    riskScore: 88,
    severityBand: "Critical",
    incidentCount: 16,
    lastAuditDate: "2026-06-28",
    daysSinceLastAudit: 24,
    correctedRate: 0.15,
    rejectedRate: 0.22,
  },
  {
    siteId: "site-010",
    siteName: "Cairns Terminal",
    riskScore: 42,
    severityBand: "Medium",
    incidentCount: 6,
    lastAuditDate: "2026-07-14",
    daysSinceLastAudit: 8,
    correctedRate: 0.04,
    rejectedRate: 0.05,
  },
  {
    siteId: "site-011",
    siteName: "Newcastle Yard",
    riskScore: 61,
    severityBand: "High",
    incidentCount: 8,
    lastAuditDate: "2026-07-08",
    daysSinceLastAudit: 14,
    correctedRate: 0.07,
    rejectedRate: 0.09,
  },
  {
    siteId: "site-012",
    siteName: "Geelong Plant",
    riskScore: 19,
    severityBand: "Low",
    incidentCount: 1,
    lastAuditDate: "2026-07-21",
    daysSinceLastAudit: 1,
    correctedRate: 0.01,
    rejectedRate: 0.0,
  },
];

// ─── Mock Alerts ────────────────────────────────────────────────────────────

export const mockAlerts: Alert[] = [
  {
    id: "alert-001",
    siteId: "site-009",
    siteName: "Gold Coast Marina",
    severity: "Critical",
    status: "active",
    title: "Data quality gate failed",
    description: "Trusted+corrected rate dropped below 90% threshold. Current rate: 63%.",
    rule: "DQ gate threshold (--fail-below 0.90)",
    recordIds: ["INC-2026-0441", "INC-2026-0442", "INC-2026-0443"],
    createdAt: "2026-07-22T08:15:00Z",
  },
  {
    id: "alert-002",
    siteId: "site-001",
    siteName: "Melbourne Central",
    severity: "Critical",
    status: "active",
    title: "High rejection rate detected",
    description: "18% of records rejected in latest batch — exceeds 10% site threshold.",
    rule: "Site rejection rate > 10%",
    recordIds: ["INC-2026-0398", "INC-2026-0399"],
    createdAt: "2026-07-22T07:45:00Z",
  },
  {
    id: "alert-003",
    siteId: "site-005",
    siteName: "Adelaide South",
    severity: "High",
    status: "active",
    title: "Audit overdue",
    description: "Last audit was 17 days ago. Threshold is 14 days for High-risk sites.",
    rule: "Audit frequency threshold (14d for High-risk)",
    recordIds: [],
    createdAt: "2026-07-22T06:00:00Z",
  },
  {
    id: "alert-004",
    siteId: "site-002",
    siteName: "Brisbane North",
    severity: "High",
    status: "acknowledged",
    title: "Incident frequency spike",
    description: "9 incidents in the last 30 days — 3× rolling average.",
    rule: "Incident frequency > 3× 90-day rolling average",
    recordIds: ["INC-2026-0370", "INC-2026-0371"],
    createdAt: "2026-07-21T14:30:00Z",
    acknowledgedAt: "2026-07-21T15:00:00Z",
    acknowledgedBy: "analyst@sentinel.io",
  },
  {
    id: "alert-005",
    siteId: "site-007",
    siteName: "Darwin Port",
    severity: "Medium",
    status: "active",
    title: "Future incident date detected",
    description: "Record INC-2026-0388 has incident_date after ingestion date.",
    rule: "No future incidents (validate.py rule)",
    recordIds: ["INC-2026-0388"],
    createdAt: "2026-07-21T10:00:00Z",
  },
  {
    id: "alert-006",
    siteId: "site-011",
    siteName: "Newcastle Yard",
    severity: "High",
    status: "resolved",
    title: "Duplicate incident IDs in batch",
    description: "Batch b-0032 contained 3 duplicate incident_id values.",
    rule: "Uniqueness (incident_id unique within batch)",
    recordIds: ["INC-2026-0350", "INC-2026-0351"],
    createdAt: "2026-07-20T16:00:00Z",
    acknowledgedAt: "2026-07-20T17:00:00Z",
    acknowledgedBy: "admin@sentinel.io",
  },
  {
    id: "alert-007",
    siteId: "site-003",
    siteName: "Sydney Harbour",
    severity: "Low",
    status: "resolved",
    title: "Score bounds violation auto-corrected",
    description: "compliance_score of 105 clamped to 100 — logged as corrected.",
    rule: "Score bounds (0–100)",
    recordIds: ["AUD-2026-0212"],
    createdAt: "2026-07-19T09:00:00Z",
    acknowledgedAt: "2026-07-19T09:15:00Z",
    acknowledgedBy: "analyst@sentinel.io",
  },
];

// ─── Mock Data Quality Summary ──────────────────────────────────────────────

export const mockQualitySummary: DataQualitySummary = {
  trusted: 1847,
  corrected: 203,
  review: 89,
  rejected: 61,
  total: 2200,
  passRate: 0.9318,
  gateStatus: "passed",
  threshold: 0.9,
  lastBatchId: "b-0034",
  lastBatchDate: "2026-07-22T08:00:00Z",
};

// ─── Mock Ingest Batches ────────────────────────────────────────────────────

export const mockBatches: IngestBatch[] = [
  {
    batchId: "b-0034",
    sourceFilename: "incidents_2026-07-22.csv",
    rowCount: 340,
    sha256Checksum: "a3f2c8e1d4b5a6f7e8d9c0b1a2f3e4d5c6b7a8f9e0d1c2b3a4f5e6d7c8b9a0f1",
    ingestedAt: "2026-07-22T08:00:00Z",
    trustedCount: 298,
    correctedCount: 22,
    reviewCount: 12,
    rejectedCount: 8,
  },
  {
    batchId: "b-0033",
    sourceFilename: "incidents_2026-07-21.csv",
    rowCount: 285,
    sha256Checksum: "b4e3d9f2a5c6b7a8e9d0c1b2a3f4e5d6c7b8a9f0e1d2c3b4a5f6e7d8c9b0a1f2",
    ingestedAt: "2026-07-21T08:00:00Z",
    trustedCount: 252,
    correctedCount: 18,
    reviewCount: 9,
    rejectedCount: 6,
  },
  {
    batchId: "b-0032",
    sourceFilename: "incidents_2026-07-20.csv",
    rowCount: 312,
    sha256Checksum: "c5f4e0a3b6d7c8b9a0e1d2c3b4a5f6e7d8c9b0a1f2e3d4c5b6a7f8e9d0c1b2a3",
    ingestedAt: "2026-07-20T08:00:00Z",
    trustedCount: 270,
    correctedCount: 25,
    reviewCount: 11,
    rejectedCount: 6,
  },
  {
    batchId: "b-0031",
    sourceFilename: "incidents_2026-07-19.csv",
    rowCount: 298,
    sha256Checksum: "d6a5f1b4c7e8d9c0b1a2f3e4d5c6b7a8f9e0d1c2b3a4f5e6d7c8b9a0f1e2d3c4",
    ingestedAt: "2026-07-19T08:00:00Z",
    trustedCount: 265,
    correctedCount: 19,
    reviewCount: 8,
    rejectedCount: 6,
  },
  {
    batchId: "b-0030",
    sourceFilename: "incidents_2026-07-18.csv",
    rowCount: 275,
    sha256Checksum: "e7b6a2c5d8f9e0d1c2b3a4f5e6d7c8b9a0f1e2d3c4b5a6f7e8d9c0b1a2f3e4d5",
    ingestedAt: "2026-07-18T08:00:00Z",
    trustedCount: 240,
    correctedCount: 20,
    reviewCount: 10,
    rejectedCount: 5,
  },
];

// ─── Mock Site Detail ───────────────────────────────────────────────────────

const mockSiteDetails: Record<string, SiteDetail> = {
  "site-001": {
    siteId: "site-001",
    siteName: "Melbourne Central",
    location: "Melbourne, VIC",
    riskScore: 82,
    severityBand: "Critical",
    incidents: [
      {
        incidentId: "INC-2026-0398",
        siteId: "site-001",
        incidentDate: "2026-07-20",
        severity: "Critical",
        description: "Unauthorized access to restricted zone — perimeter breach detected by sensor grid.",
        complianceScore: 28,
        decision: "rejected",
        decisionReason: "compliance_score below hard threshold (30)",
      },
      {
        incidentId: "INC-2026-0399",
        siteId: "site-001",
        incidentDate: "2026-07-19",
        severity: "High",
        description: "Chemical storage temperature exceeded safe range for 4+ hours.",
        complianceScore: 52,
        decision: "review",
        decisionReason: "Severity High + compliance_score in ambiguous range (40-60)",
      },
      {
        incidentId: "INC-2026-0385",
        siteId: "site-001",
        incidentDate: "2026-07-15",
        severity: "Medium",
        description: "PPE non-compliance observed during routine check.",
        complianceScore: 75,
        decision: "trusted",
        decisionReason: "All validation rules pass",
      },
      {
        incidentId: "INC-2026-0372",
        siteId: "site-001",
        incidentDate: "2026-07-10",
        severity: "High",
        description: "Fire suppression system offline for scheduled maintenance — extended beyond window.",
        complianceScore: 60,
        decision: "corrected",
        decisionReason: "severity normalized from 'high' to 'High' (case correction)",
        closedDate: "2026-07-12",
      },
    ],
    audits: [
      {
        auditId: "AUD-2026-0198",
        siteId: "site-001",
        inspectionDate: "2026-07-01",
        auditor: "J. Thompson",
        findings: "3 non-conformances identified: emergency exit signage, chemical labeling, access logs incomplete.",
        complianceScore: 61,
        followUpRequired: true,
      },
      {
        auditId: "AUD-2026-0185",
        siteId: "site-001",
        inspectionDate: "2026-06-15",
        auditor: "M. Chen",
        findings: "Satisfactory overall. Minor issue with equipment calibration records.",
        complianceScore: 78,
        followUpRequired: false,
      },
    ],
  },
  "site-009": {
    siteId: "site-009",
    siteName: "Gold Coast Marina",
    location: "Gold Coast, QLD",
    riskScore: 88,
    severityBand: "Critical",
    incidents: [
      {
        incidentId: "INC-2026-0441",
        siteId: "site-009",
        incidentDate: "2026-07-21",
        severity: "Critical",
        description: "Structural integrity alert — dock C section 4 weight limit exceeded.",
        complianceScore: 15,
        decision: "rejected",
        decisionReason: "compliance_score below hard threshold (30)",
      },
      {
        incidentId: "INC-2026-0442",
        siteId: "site-009",
        incidentDate: "2026-07-21",
        severity: "Critical",
        description: "Oil spill detected in berth area — containment protocols activated.",
        complianceScore: 22,
        decision: "rejected",
        decisionReason: "compliance_score below hard threshold (30)",
      },
      {
        incidentId: "INC-2026-0443",
        siteId: "site-009",
        incidentDate: "2026-07-20",
        severity: "High",
        description: "Navigation light system failure — vessels rerouted.",
        complianceScore: 48,
        decision: "review",
        decisionReason: "Severity High + compliance_score in ambiguous range (40-60)",
      },
    ],
    audits: [
      {
        auditId: "AUD-2026-0201",
        siteId: "site-009",
        inspectionDate: "2026-06-28",
        auditor: "R. Patel",
        findings: "5 critical non-conformances: structural maintenance overdue, safety equipment expired, dock lighting inadequate, waste management non-compliant, access control gaps.",
        complianceScore: 34,
        followUpRequired: true,
      },
    ],
  },
};

export function getMockSiteDetail(siteId: string): SiteDetail {
  if (mockSiteDetails[siteId]) {
    return mockSiteDetails[siteId];
  }

  // Generate a generic detail for sites without explicit mock data
  const site = mockSites.find((s) => s.siteId === siteId);
  return {
    siteId,
    siteName: site?.siteName ?? `Site ${siteId}`,
    location: "Unknown",
    riskScore: site?.riskScore ?? 0,
    severityBand: site?.severityBand ?? "Low",
    incidents: [],
    audits: [],
  };
}

// ─── Mock Compliance Data ───────────────────────────────────────────────────

export const mockComplianceNetwork: ComplianceNetworkSummary = {
  networkOcs: 82.4,
  networkSafetyScore: 79.8,
  networkEnvironmentalScore: 85.2,
  networkAssetIntegrityScore: 81.6,
  networkRegulatoryScore: 83.9,
  networkRag: "AMBER",
  totalOpenViolations: 14,
  totalCriticalViolations: 3,
  calculatedAt: "2026-07-24T06:00:00Z",
  sites: [
    { siteId: "kpc-msa",   siteName: "Mombasa Terminal",      region: "Coast",       criticality: "Critical", overallScore: 74.1, overallRag: "RED",   safetyScore: 68.0, safetyRag: "RED",   environmentalScore: 80.0, environmentalRag: "AMBER", assetIntegrityScore: 76.0, assetIntegrityRag: "AMBER", regulatoryScore: 75.0, regulatoryRag: "AMBER", openViolations: 3 },
    { siteId: "kpc-nbi",   siteName: "Nairobi Depot",          region: "Nairobi",     criticality: "Critical", overallScore: 83.6, overallRag: "AMBER", safetyScore: 82.0, safetyRag: "AMBER", environmentalScore: 88.0, environmentalRag: "GREEN", assetIntegrityScore: 82.0, assetIntegrityRag: "AMBER", regulatoryScore: 83.0, regulatoryRag: "AMBER", openViolations: 2 },
    { siteId: "kpc-nkr",   siteName: "Nakuru Station",         region: "Rift Valley", criticality: "High",     overallScore: 78.3, overallRag: "AMBER", safetyScore: 80.0, safetyRag: "AMBER", environmentalScore: 84.0, environmentalRag: "AMBER", assetIntegrityScore: 71.0, assetIntegrityRag: "RED",   regulatoryScore: 80.0, regulatoryRag: "AMBER", openViolations: 2 },
    { siteId: "kpc-eld",   siteName: "Eldoret Station",        region: "Rift Valley", criticality: "High",     overallScore: 71.2, overallRag: "RED",   safetyScore: 75.0, safetyRag: "AMBER", environmentalScore: 82.0, environmentalRag: "AMBER", assetIntegrityScore: 62.0, assetIntegrityRag: "RED",   regulatoryScore: 78.0, regulatoryRag: "AMBER", openViolations: 3 },
    { siteId: "kpc-ksm",   siteName: "Kisumu Depot",           region: "Nyanza",      criticality: "High",     overallScore: 88.0, overallRag: "GREEN", safetyScore: 90.0, safetyRag: "GREEN", environmentalScore: 91.0, environmentalRag: "GREEN", assetIntegrityScore: 85.0, assetIntegrityRag: "AMBER", regulatoryScore: 87.0, regulatoryRag: "GREEN", openViolations: 1 },
    { siteId: "kpc-nbi-w", siteName: "Nairobi West Station",   region: "Nairobi",     criticality: "Critical", overallScore: 72.5, overallRag: "RED",   safetyScore: 74.0, safetyRag: "RED",   environmentalScore: 70.0, environmentalRag: "RED",   assetIntegrityScore: 72.0, assetIntegrityRag: "RED",   regulatoryScore: 75.0, regulatoryRag: "AMBER", openViolations: 3 },
    { siteId: "kpc-kak",   siteName: "Kakamega Station",       region: "Western",     criticality: "Medium",   overallScore: 86.4, overallRag: "AMBER", safetyScore: 89.0, safetyRag: "GREEN", environmentalScore: 84.0, environmentalRag: "AMBER", assetIntegrityScore: 87.0, assetIntegrityRag: "GREEN", regulatoryScore: 86.0, regulatoryRag: "AMBER", openViolations: 0 },
    { siteId: "kpc-gil",   siteName: "Gilgil Station",         region: "Rift Valley", criticality: "Medium",   overallScore: 70.0, overallRag: "RED",   safetyScore: 65.0, safetyRag: "RED",   environmentalScore: 80.0, environmentalRag: "AMBER", assetIntegrityScore: 72.0, assetIntegrityRag: "RED",   regulatoryScore: 78.0, regulatoryRag: "AMBER", openViolations: 2 },
    { siteId: "kpc-nai-s", siteName: "Nairobi South Depot",    region: "Nairobi",     criticality: "High",     overallScore: 95.2, overallRag: "GREEN", safetyScore: 96.0, safetyRag: "GREEN", environmentalScore: 95.0, environmentalRag: "GREEN", assetIntegrityScore: 95.0, assetIntegrityRag: "GREEN", regulatoryScore: 95.0, regulatoryRag: "GREEN", openViolations: 0 },
    { siteId: "kpc-thk",   siteName: "Thika Station",          region: "Central",     criticality: "Medium",   overallScore: 90.1, overallRag: "GREEN", safetyScore: 92.0, safetyRag: "GREEN", environmentalScore: 91.0, environmentalRag: "GREEN", assetIntegrityScore: 89.0, assetIntegrityRag: "GREEN", regulatoryScore: 89.0, regulatoryRag: "GREEN", openViolations: 0 },
  ],
};

export const mockViolations: ComplianceViolation[] = [
  { id: 1, ruleId: "BR-S03", ruleName: "PTW Authorisation Before High-Risk Work",    indicatorId: "PTWCI", domainId: "SCD",  siteId: "kpc-msa",   siteName: "Mombasa Terminal",    assetReference: "KPC-INC-0002", severity: "Critical", violationDate: "2026-07-03", description: "Hot work commenced on Mombasa manifold without valid PTW.",                          recommendedAction: "Immediate stop-work; mandatory PTW refresher for all supervisors.",                        status: "OPEN",  closedDate: null, createdAt: "2026-07-22T08:00:00Z" },
  { id: 2, ruleId: "BR-A04", ruleName: "Leak Detection System Availability",          indicatorId: "LDCI",  domainId: "AICD", siteId: "kpc-eld",   siteName: "Eldoret Station",     assetReference: "KPC-INC-0005", severity: "Critical", violationDate: "2026-07-08", description: "SCADA CPM unavailable for 2.5 hours — KPC-ELD-012.",                                         recommendedAction: "Immediate SCADA team alert; manual patrol during downtime; investigate root cause.",        status: "OPEN",  closedDate: null, createdAt: "2026-07-22T08:00:00Z" },
  { id: 3, ruleId: "BR-S03", ruleName: "PTW Authorisation Before High-Risk Work",    indicatorId: "PTWCI", domainId: "SCD",  siteId: "kpc-gil",   siteName: "Gilgil Station",      assetReference: "KPC-INC-0014", severity: "Critical", violationDate: "2026-07-19", description: "Confined space entry without completed gas test at Gilgil.",                                  recommendedAction: "Stop-work; disciplinary review; mandatory confined space PTW re-briefing.",                status: "OPEN",  closedDate: null, createdAt: "2026-07-22T08:00:00Z" },
  { id: 4, ruleId: "BR-A01", ruleName: "Asset Inspection Not Overdue",                indicatorId: "ICI",   domainId: "AICD", siteId: "kpc-nbi-w", siteName: "Nairobi West Station", assetReference: "KPC-NBW-PV-003", severity: "High",   violationDate: "2026-07-20", description: "Pressure vessel KPC-NBW-PV-003 inspection 38 days overdue.",                                  recommendedAction: "Schedule inspection immediately; conduct risk assessment pending inspection.",               status: "OPEN",  closedDate: null, createdAt: "2026-07-22T08:00:00Z" },
  { id: 5, ruleId: "BR-E01", ruleName: "Water Discharge Parameter Within NEMA Limits",indicatorId: "WQCI",  domainId: "ECD",  siteId: "kpc-nbi-w", siteName: "Nairobi West Station", assetReference: "KPC-INC-0007", severity: "High",    violationDate: "2026-07-11", description: "TPH level 1.4× NEMA permitted limit at Nairobi West Station.",                                recommendedAction: "Identify source; isolate discharge; notify NEMA within 24h; inspect oil/water separator.", status: "OPEN",  closedDate: null, createdAt: "2026-07-22T08:00:00Z" },
  { id: 6, ruleId: "BR-A03", ruleName: "Corrosion Monitoring Point Coverage",         indicatorId: "CMCI",  domainId: "AICD", siteId: "kpc-nkr",   siteName: "Nakuru Station",      assetReference: "KPC-NKR-012",  severity: "High",    violationDate: "2026-07-14", description: "Segment KPC-NKR-012 corrosion monitoring point 18 days past required interval.",             recommendedAction: "Dispatch corrosion technician; verify CP system; schedule immediate reading.",              status: "OPEN",  closedDate: null, createdAt: "2026-07-22T08:00:00Z" },
  { id: 7, ruleId: "BR-R02", ruleName: "Corrective Action Closed By Target Date",    indicatorId: "CACI",  domainId: "RCD",  siteId: "kpc-nbi",   siteName: "Nairobi Depot",       assetReference: "CAR-2026-0047", severity: "High",   violationDate: "2026-06-13", description: "CAR-2026-0047 (leak detection calibration, Nakuru) is 41 days past target date.",             recommendedAction: "Escalate to Maintenance Superintendent; resolve within 5 working days.",                   status: "OPEN",  closedDate: null, createdAt: "2026-07-22T08:00:00Z" },
  { id: 8, ruleId: "BR-S01", ruleName: "PPE Field Observation Compliance",           indicatorId: "PCI",   domainId: "SCD",  siteId: "kpc-msa",   siteName: "Mombasa Terminal",    assetReference: "KPC-INC-0001", severity: "High",    violationDate: "2026-07-01", description: "3 workers observed without hard hats in pump hall.",                                          recommendedAction: "Issue verbal warning; toolbox talk within 24h; re-inspect within 48h.",                    status: "OPEN",  closedDate: null, createdAt: "2026-07-22T08:00:00Z" },
];

export const mockComplianceTrend: ComplianceTrendPoint[] = [
  { weekStart: "2026-05-19", ocsScore: 88.2, safetyScore: 86.0, environmentalScore: 90.1, assetIntegrityScore: 87.5, regulatoryScore: 89.2 },
  { weekStart: "2026-05-26", ocsScore: 87.6, safetyScore: 85.4, environmentalScore: 89.8, assetIntegrityScore: 86.8, regulatoryScore: 88.7 },
  { weekStart: "2026-06-02", ocsScore: 86.9, safetyScore: 84.9, environmentalScore: 89.2, assetIntegrityScore: 85.9, regulatoryScore: 88.0 },
  { weekStart: "2026-06-09", ocsScore: 86.1, safetyScore: 84.1, environmentalScore: 88.6, assetIntegrityScore: 85.0, regulatoryScore: 87.2 },
  { weekStart: "2026-06-16", ocsScore: 85.4, safetyScore: 83.4, environmentalScore: 87.9, assetIntegrityScore: 84.2, regulatoryScore: 86.5 },
  { weekStart: "2026-06-23", ocsScore: 84.8, safetyScore: 82.8, environmentalScore: 87.3, assetIntegrityScore: 83.4, regulatoryScore: 85.8 },
  { weekStart: "2026-06-30", ocsScore: 84.0, safetyScore: 82.1, environmentalScore: 86.6, assetIntegrityScore: 82.5, regulatoryScore: 85.0 },
  { weekStart: "2026-07-07", ocsScore: 83.3, safetyScore: 81.4, environmentalScore: 86.0, assetIntegrityScore: 81.7, regulatoryScore: 84.3 },
  { weekStart: "2026-07-14", ocsScore: 83.5, safetyScore: 80.8, environmentalScore: 86.4, assetIntegrityScore: 82.8, regulatoryScore: 84.8 },
  { weekStart: "2026-07-21", ocsScore: 82.4, safetyScore: 79.8, environmentalScore: 85.2, assetIntegrityScore: 81.6, regulatoryScore: 83.9 },
];

export function getMockComplianceSite(siteId: string): ComplianceSummary {
  const card = mockComplianceNetwork.sites.find((s) => s.siteId === siteId);
  const name = card?.siteName ?? siteId;
  return {
    siteId,
    siteName: name,
    overallScore: card?.overallScore ?? 82.4,
    overallRag: card?.overallRag ?? "AMBER",
    openViolationCount: card?.openViolations ?? 0,
    criticalViolationCount: 0,
    periodStart: "2026-06-24",
    periodEnd: "2026-07-24",
    calculatedAt: "2026-07-24T06:00:00Z",
    domains: [
      { domainId: "SCD",  domainName: "Safety Compliance",          domainWeight: 0.30, score: card?.safetyScore ?? 80,           ragStatus: card?.safetyRag ?? "AMBER",           displayOrder: 1, indicators: [] },
      { domainId: "ECD",  domainName: "Environmental Compliance",   domainWeight: 0.25, score: card?.environmentalScore ?? 85,    ragStatus: card?.environmentalRag ?? "AMBER",    displayOrder: 2, indicators: [] },
      { domainId: "AICD", domainName: "Asset Integrity Compliance", domainWeight: 0.25, score: card?.assetIntegrityScore ?? 82,   ragStatus: card?.assetIntegrityRag ?? "AMBER",   displayOrder: 3, indicators: [] },
      { domainId: "RCD",  domainName: "Regulatory Compliance",      domainWeight: 0.20, score: card?.regulatoryScore ?? 84,       ragStatus: card?.regulatoryRag ?? "GREEN",       displayOrder: 4, indicators: [] },
    ],
  };
}
