-- =============================================================================
-- V38: Restore narrative columns on the alerts table
-- =============================================================================
-- Migrations V11 (narrative), V12 (narrative_updated_at), and V13
-- (narrative_incident_count) were moved to _migration_archive_disabled/ and
-- are no longer applied by Flyway.  This migration re-adds the same three
-- columns using IF NOT EXISTS so it is safe to run on any DB state:
--   • Fresh DB (V1–V5 only)   → columns created here
--   • DB with V11/V12/V13 run → no-op, columns already exist
-- =============================================================================

ALTER TABLE alerts ADD COLUMN IF NOT EXISTS narrative TEXT;

ALTER TABLE alerts ADD COLUMN IF NOT EXISTS narrative_updated_at TIMESTAMP;

ALTER TABLE alerts ADD COLUMN IF NOT EXISTS narrative_incident_count BIGINT DEFAULT 0;

COMMENT ON COLUMN alerts.narrative
    IS 'Rich human-readable narrative generated by NarrativeService at alert-creation time.';

COMMENT ON COLUMN alerts.narrative_updated_at
    IS 'Timestamp of when the narrative was last written or refreshed.';

COMMENT ON COLUMN alerts.narrative_incident_count
    IS 'Incident count used when the current narrative was generated (staleness check).';
